### ISSUE TITLE
Port PSD to html

### ISSUE THREAD

**Issue by alezucca** [alezucca/alessia2017#1]

**Comment by alezucca** [comment]
[blog.psd.zip](https://github.com/alezucca/alessia2017/files/679893/blog.psd.zip)

**Comment by alezucca** [comment]
Screenshot ![blog_page_screenshot](https://cloud.githubusercontent.com/assets/19538358/21579881/8f6d474c-cfc1-11e6-9ca7-3e7ce961d662.png)

**Comment by alezucca** [comment]
PSD: [blog_page.psd.zip](https://github.com/alezucca/alessia2017/files/679895/blog_page.psd.zip)

**Comment by dimitraz** [comment]
To Do: 

- [ ]  Single post page
- [ ] Search page
- [ ] Categories & Author pages
