### ISSUE TITLE
Handling photo galleries 

### ISSUE THREAD

**Issue by dimitraz** [alezucca/alessia2017#11]
Need to find a way to handle displaying groups of images on a single post page

**Comment by marcotroisi** [comment]
Do you mean like a gallery or more like a grid?

**Comment by marcotroisi** [comment]
https://wordpress.org/plugins/responsive-gallery-grid/screenshots/ ?

**Comment by dimitraz** [comment]
Yes, probably more of a grid. It would be nice to automate grids based on height/width of photos inserted, or allow several options for different types of grids

**Comment by dimitraz** [comment]
Example from Tumblr:
<img width="537" alt="screen shot 2017-01-03 at 15 12 25" src="https://cloud.githubusercontent.com/assets/8274693/21612113/bdaf22da-d1c7-11e6-9452-3c74483f7e0a.png">

**Comment by dimitraz** [comment]
@marcotroisi @alezucca What do we think?

<img width="1434" alt="screen shot 2017-01-03 at 15 28 59" src="https://cloud.githubusercontent.com/assets/8274693/21612567/b1de1392-d1c9-11e6-8547-852549fa9347.png">
<img width="1423" alt="screen shot 2017-01-03 at 15 29 02" src="https://cloud.githubusercontent.com/assets/8274693/21612568/b2124248-d1c9-11e6-8a07-5ef39690dcf0.png">

**Comment by alezucca** [comment]
very nice

**Comment by dimitraz** [comment]
Cool beans, its really easy to use. Plug and play
