### ISSUE TITLE
Home page excerpt

### ISSUE THREAD

**Issue by alezucca** [alezucca/alessia2017#19]
Would it be possible to create an automated excerpt on the homepage to avoid words being chopped up?

**Comment by dimitraz** [comment]
Yes, good idea. I've also been meaning to add a `"Read more"` link

**Comment by alezucca** [comment]
Good idea on the read more. I tried to go back and insert manual read more tags but they don't work: (look at first post)
![screen shot 2017-01-04 at 11 49 46](https://cloud.githubusercontent.com/assets/19538358/21641484/02912fd6-d274-11e6-9bfd-95f0a400ec90.png)

**Comment by alezucca** [comment]
actually it works when I put the manual break after the first 20 words or so

**Comment by dimitraz** [comment]
Do you prefer the longer excerpt or a shorter one?
