### ISSUE TITLE
About page issue

### ISSUE THREAD

**Issue by piccolazucca** [alezucca/alessia2017#23]
It ends too abruptly, maybe
- Add an "x" to the bottom of the page to funnel it out
- An ornament could be another idea
- Possibly a footer 

Thoughts?

**Comment by alezucca** [comment]
Yes, leave it to me

**Comment by alezucca** [comment]
done.. @piccolazucca does it need related posts and author like post page in your opinion?

**Comment by piccolazucca** [comment]
No related posts in my opinion! It's good how it is now hey
