### ISSUE TITLE
forced lowercase on home page

### ISSUE THREAD

**Issue by alezucca** [alezucca/alessia2017#28]
Titles have forced lowercase on homepage but regular on post pages. I think it would look nicer without text transform:

![screen shot 2017-01-04 at 10 57 41](https://cloud.githubusercontent.com/assets/19538358/21640285/b82a1f9a-d26c-11e6-89b2-35bbc8b73d81.png)

**Comment by alezucca** [comment]
@dimitraz @piccolazucca I updated it, what do you think?

**Comment by dimitraz** [comment]
@alezucca Can you post a screenshot?
